name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Create directories
        run: |
          mkdir -p dist          
          mkdir -p target          
          mkdir -p node_modules          

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:                      
          push: never
          runCmd: |
            id
            ls -lah
            cargo test --all-targets --all-features
            cargo clippy --all-targets --all-features -- -D warnings            
            cargo build
            npm install  
            npm run build
      
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 7
