name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Create directories
        run: |
          mkdir dist
          touch dist/.gitkeep
          mkdir target
          touch target/.gitkeep
          mkdir node_modules
          touch node_modules/.gitkeep

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:                      
          runCmd: |
            cargo test --all-targets --all-features
            cargo clippy --all-targets --all-features -- -D warnings            
            id
            ls -lah
            cargo build
            npm install  
            npm run build
      
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 7
