name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Create directories and set permissions
        run: |
          mkdir dist          
          mkdir target          
          mkdir node_modules
          sudo chown -R 1000:1000 .

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with: 
          skipContainerUserIdUpdate: false
          push: never
          runCmd: |
            id
            ls -lah
            cargo test --all-targets --all-features
            cargo clippy --all-targets --all-features -- -D warnings            
            cargo build
            npm install  
            npm run build
                
      - name: Restore permissions
        run: |
          sudo chown -R 1001:999 .
        
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 7
